describe("COMP229SEC002F25-REC", () => {
  it("tests COMP229SEC002F25-REC", () => {
    cy.viewport(1706, 819);
    cy.visit("http://localhost:3000/");
    cy.get("a:nth-of-type(2) > button").click();
    cy.get("#root > div > div a:nth-of-type(3)").click();
    cy.get("#root > div > div path").click();
    cy.get("#root > div > div a:nth-of-type(2) > button").click();
    cy.get("a:nth-of-type(2) > button").click();
    cy.get("#root > div > div a:nth-of-type(3)").click();
    cy.get("#root > div > div path").click();
    cy.get("a:nth-of-type(3) > button").click();
    cy.get("a:nth-of-type(6) > button").click();
    cy.get("a:nth-of-type(4) > button").click();
    cy.get("#root > div > div a:nth-of-type(1) > button").click();
    cy.get("#email").click();
    cy.get("#email").type("joke@yahoo.com");
    cy.get("#password").click();
    cy.get("#password").type("jokejoke");
    cy.get("#root > div > div button").click();
    cy.get("a:nth-of-type(6) > button").click();
    cy.get("#root > div > div a path").click();
    cy.get("a:nth-of-type(5) > button").click();
    cy.get("h6 button").click();
    cy.get("label > span").click();
    cy.get("#icon-button-file").type("C:\\fakepath\\COMP213.jpg");
    cy.get("#name").click();
    cy.get("#name").type("Textbook");
    cy.get("#description").click();
    cy.get("#description").type("Web Textbook");
    cy.get("div.MuiCardActions-root > button").click();
    cy.get("#root > div > div > div:nth-of-type(2) button").click();
    cy.get("label > span").click();
    cy.get("#icon-button-file").type("C:\\fakepath\\vengeance3.jpg");
    cy.get("#name").click();
    cy.get("#name").type("dyfygf");
    cy.get("#multiline-flexible").type("yfyfyf");
    cy.get("#category").type("fyfyf");
    cy.get("#quantity").type("7");
    cy.get("#price").type("45");
    cy.get("div.MuiCardActions-root > button").click();
    cy.get("#name").click();
    cy.get("#name").type("Textbook89");
    cy.get("#root > div > div > div:nth-of-type(1) button").click();
    cy.get("a:nth-of-type(3) > button").click();
    cy.get("a:nth-of-type(5) > button").click();
    cy.get("header > div > button").click();
  });
});
//# recorderSourceMap=BCBDBEBFBGBHBIBJBKBLBMBNBOBPBQBRBSBTBUBVBWBXBYBZBaBbBcBdBeBfBgBBhBBiBBjBBkBAkBAkBBlBAlBAlBBmBAmBAmBBnBAnBAnBBoBBpBBqBBrBBsBBtBBuBB
